/**
 * The instrument master. Symbols are the canonical bare NSE form.
 * `seedPrice` is only a placeholder so the app is usable before the first EOD
 * sync — real closes overwrite it. Add rows freely; run `npm run seed` again,
 * which upserts rather than duplicating.
 */
module.exports = [
  { symbol: 'RELIANCE',   name: 'Reliance Industries',        sector: 'Energy',         seedPrice: 1428 },
  { symbol: 'TCS',        name: 'Tata Consultancy Services',  sector: 'IT',             seedPrice: 3105 },
  { symbol: 'HDFCBANK',   name: 'HDFC Bank',                  sector: 'Banking',        seedPrice: 1682 },
  { symbol: 'INFY',       name: 'Infosys',                    sector: 'IT',             seedPrice: 1547 },
  { symbol: 'ICICIBANK',  name: 'ICICI Bank',                 sector: 'Banking',        seedPrice: 1298 },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel',              sector: 'Telecom',        seedPrice: 1740 },
  { symbol: 'SBIN',       name: 'State Bank of India',        sector: 'Banking',        seedPrice: 812 },
  { symbol: 'ITC',        name: 'ITC',                        sector: 'FMCG',           seedPrice: 412 },
  { symbol: 'LT',         name: 'Larsen & Toubro',            sector: 'Infrastructure', seedPrice: 3618 },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever',         sector: 'FMCG',           seedPrice: 2340 },
  { symbol: 'AXISBANK',   name: 'Axis Bank',                  sector: 'Banking',        seedPrice: 1118 },
  { symbol: 'KOTAKBANK',  name: 'Kotak Mahindra Bank',        sector: 'Banking',        seedPrice: 1795 },
  { symbol: 'MARUTI',     name: 'Maruti Suzuki India',        sector: 'Auto',           seedPrice: 12480 },
  { symbol: 'M&M',        name: 'Mahindra & Mahindra',        sector: 'Auto',           seedPrice: 2960 },
  { symbol: 'SUNPHARMA',  name: 'Sun Pharmaceutical',         sector: 'Pharma',         seedPrice: 1712 },
  { symbol: 'CIPLA',      name: 'Cipla',                      sector: 'Pharma',         seedPrice: 1495 },
  { symbol: 'TATAMOTORS', name: 'Tata Motors',                sector: 'Auto',           seedPrice: 712 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance',              sector: 'NBFC',           seedPrice: 8905 },
  { symbol: 'ASIANPAINT', name: 'Asian Paints',               sector: 'Paints',         seedPrice: 2418 },
  { symbol: 'TITAN',      name: 'Titan Company',              sector: 'Consumer',       seedPrice: 3340 },
  { symbol: 'WIPRO',      name: 'Wipro',                      sector: 'IT',             seedPrice: 258 },
  { symbol: 'HCLTECH',    name: 'HCL Technologies',           sector: 'IT',             seedPrice: 1685 },
  { symbol: 'ADANIENT',   name: 'Adani Enterprises',          sector: 'Conglomerate',   seedPrice: 2385 },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ',          sector: 'Infrastructure', seedPrice: 1310 },
  { symbol: 'ZOMATO',     name: 'Eternal (Zomato)',           sector: 'Internet',       seedPrice: 268 },
  { symbol: 'PAYTM',      name: 'One97 Communications',       sector: 'Fintech',        seedPrice: 885 },
  { symbol: 'NYKAA',      name: 'FSN E-Commerce (Nykaa)',     sector: 'Internet',       seedPrice: 192 },
  { symbol: 'DMART',      name: 'Avenue Supermarts',          sector: 'Retail',         seedPrice: 4120 },
  { symbol: 'IRCTC',      name: 'IRCTC',                      sector: 'Travel',         seedPrice: 742 },
  { symbol: 'TATASTEEL',  name: 'Tata Steel',                 sector: 'Metals',         seedPrice: 148 },
  { symbol: 'JSWSTEEL',   name: 'JSW Steel',                  sector: 'Metals',         seedPrice: 985 },
  { symbol: 'JIOFIN',     name: 'Jio Financial Services',     sector: 'NBFC',           seedPrice: 312 },
  { symbol: 'IDEA',       name: 'Vodafone Idea',              sector: 'Telecom',        seedPrice: 8.4 },
  { symbol: 'ONGC',       name: 'Oil & Natural Gas Corp',     sector: 'Energy',         seedPrice: 245 },
  { symbol: 'NTPC',       name: 'NTPC',                       sector: 'Power',          seedPrice: 348 },
  { symbol: 'POWERGRID',  name: 'Power Grid Corporation',     sector: 'Power',          seedPrice: 292 },
  { symbol: 'COALINDIA',  name: 'Coal India',                 sector: 'Mining',         seedPrice: 385 },
  { symbol: 'NESTLEIND',  name: 'Nestle India',               sector: 'FMCG',           seedPrice: 2210 },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement',           sector: 'Cement',         seedPrice: 11450 },
  { symbol: 'DIVISLAB',   name: 'Divi\'s Laboratories',       sector: 'Pharma',         seedPrice: 5890 },
  { symbol: 'TECHM',      name: 'Tech Mahindra',              sector: 'IT',             seedPrice: 1620 },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank',              sector: 'Banking',        seedPrice: 795 },
  { symbol: 'DRREDDY',    name: 'Dr. Reddy\'s Laboratories',  sector: 'Pharma',         seedPrice: 1265 },
  { symbol: 'GRASIM',     name: 'Grasim Industries',          sector: 'Conglomerate',   seedPrice: 2680 },
  { symbol: 'HINDALCO',   name: 'Hindalco Industries',        sector: 'Metals',         seedPrice: 685 },
  { symbol: 'VBL',        name: 'Varun Beverages',            sector: 'FMCG',           seedPrice: 512 },
  { symbol: 'TRENT',      name: 'Trent',                      sector: 'Retail',         seedPrice: 5420 },
  { symbol: 'DIXON',      name: 'Dixon Technologies',         sector: 'Electronics',    seedPrice: 15800 },
  { symbol: 'POLICYBZR',  name: 'PB Fintech (Policybazaar)',  sector: 'Fintech',        seedPrice: 1725 },
  { symbol: 'HAL',        name: 'Hindustan Aeronautics',      sector: 'Defence',        seedPrice: 4280 },
];